defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: chimpance99
  socket: /tmp/mysql.sock

development:
  database: stereosonica_development
  <<: *defaults

test: &test
  database: stereosonica_test
  <<: *defaults

production:
  host: localhost
  database: stereosonica_production
  <<: *defaults
