require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AuspiciadoresController do

  # This should return the minimal set of attributes required to create a valid
  # Auspiciador. As you add validations to Auspiciador, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "link" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AuspiciadoresController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all auspiciadores as @auspiciadores" do
      auspiciador = Auspiciador.create! valid_attributes
      get :index, {}, valid_session
      assigns(:auspiciadores).should eq([auspiciador])
    end
  end

  describe "GET show" do
    it "assigns the requested auspiciador as @auspiciador" do
      auspiciador = Auspiciador.create! valid_attributes
      get :show, {:id => auspiciador.to_param}, valid_session
      assigns(:auspiciador).should eq(auspiciador)
    end
  end

  describe "GET new" do
    it "assigns a new auspiciador as @auspiciador" do
      get :new, {}, valid_session
      assigns(:auspiciador).should be_a_new(Auspiciador)
    end
  end

  describe "GET edit" do
    it "assigns the requested auspiciador as @auspiciador" do
      auspiciador = Auspiciador.create! valid_attributes
      get :edit, {:id => auspiciador.to_param}, valid_session
      assigns(:auspiciador).should eq(auspiciador)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Auspiciador" do
        expect {
          post :create, {:auspiciador => valid_attributes}, valid_session
        }.to change(Auspiciador, :count).by(1)
      end

      it "assigns a newly created auspiciador as @auspiciador" do
        post :create, {:auspiciador => valid_attributes}, valid_session
        assigns(:auspiciador).should be_a(Auspiciador)
        assigns(:auspiciador).should be_persisted
      end

      it "redirects to the created auspiciador" do
        post :create, {:auspiciador => valid_attributes}, valid_session
        response.should redirect_to(Auspiciador.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved auspiciador as @auspiciador" do
        # Trigger the behavior that occurs when invalid params are submitted
        Auspiciador.any_instance.stub(:save).and_return(false)
        post :create, {:auspiciador => { "link" => "invalid value" }}, valid_session
        assigns(:auspiciador).should be_a_new(Auspiciador)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Auspiciador.any_instance.stub(:save).and_return(false)
        post :create, {:auspiciador => { "link" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested auspiciador" do
        auspiciador = Auspiciador.create! valid_attributes
        # Assuming there are no other auspiciadores in the database, this
        # specifies that the Auspiciador created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Auspiciador.any_instance.should_receive(:update_attributes).with({ "link" => "MyString" })
        put :update, {:id => auspiciador.to_param, :auspiciador => { "link" => "MyString" }}, valid_session
      end

      it "assigns the requested auspiciador as @auspiciador" do
        auspiciador = Auspiciador.create! valid_attributes
        put :update, {:id => auspiciador.to_param, :auspiciador => valid_attributes}, valid_session
        assigns(:auspiciador).should eq(auspiciador)
      end

      it "redirects to the auspiciador" do
        auspiciador = Auspiciador.create! valid_attributes
        put :update, {:id => auspiciador.to_param, :auspiciador => valid_attributes}, valid_session
        response.should redirect_to(auspiciador)
      end
    end

    describe "with invalid params" do
      it "assigns the auspiciador as @auspiciador" do
        auspiciador = Auspiciador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Auspiciador.any_instance.stub(:save).and_return(false)
        put :update, {:id => auspiciador.to_param, :auspiciador => { "link" => "invalid value" }}, valid_session
        assigns(:auspiciador).should eq(auspiciador)
      end

      it "re-renders the 'edit' template" do
        auspiciador = Auspiciador.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Auspiciador.any_instance.stub(:save).and_return(false)
        put :update, {:id => auspiciador.to_param, :auspiciador => { "link" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested auspiciador" do
      auspiciador = Auspiciador.create! valid_attributes
      expect {
        delete :destroy, {:id => auspiciador.to_param}, valid_session
      }.to change(Auspiciador, :count).by(-1)
    end

    it "redirects to the auspiciadores list" do
      auspiciador = Auspiciador.create! valid_attributes
      delete :destroy, {:id => auspiciador.to_param}, valid_session
      response.should redirect_to(auspiciadores_url)
    end
  end

end
