require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DiapositivasController do

  # This should return the minimal set of attributes required to create a valid
  # Diapositiva. As you add validations to Diapositiva, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "pie_de_foto" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiapositivasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all diapositivas as @diapositivas" do
      diapositiva = Diapositiva.create! valid_attributes
      get :index, {}, valid_session
      assigns(:diapositivas).should eq([diapositiva])
    end
  end

  describe "GET show" do
    it "assigns the requested diapositiva as @diapositiva" do
      diapositiva = Diapositiva.create! valid_attributes
      get :show, {:id => diapositiva.to_param}, valid_session
      assigns(:diapositiva).should eq(diapositiva)
    end
  end

  describe "GET new" do
    it "assigns a new diapositiva as @diapositiva" do
      get :new, {}, valid_session
      assigns(:diapositiva).should be_a_new(Diapositiva)
    end
  end

  describe "GET edit" do
    it "assigns the requested diapositiva as @diapositiva" do
      diapositiva = Diapositiva.create! valid_attributes
      get :edit, {:id => diapositiva.to_param}, valid_session
      assigns(:diapositiva).should eq(diapositiva)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Diapositiva" do
        expect {
          post :create, {:diapositiva => valid_attributes}, valid_session
        }.to change(Diapositiva, :count).by(1)
      end

      it "assigns a newly created diapositiva as @diapositiva" do
        post :create, {:diapositiva => valid_attributes}, valid_session
        assigns(:diapositiva).should be_a(Diapositiva)
        assigns(:diapositiva).should be_persisted
      end

      it "redirects to the created diapositiva" do
        post :create, {:diapositiva => valid_attributes}, valid_session
        response.should redirect_to(Diapositiva.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved diapositiva as @diapositiva" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diapositiva.any_instance.stub(:save).and_return(false)
        post :create, {:diapositiva => { "pie_de_foto" => "invalid value" }}, valid_session
        assigns(:diapositiva).should be_a_new(Diapositiva)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diapositiva.any_instance.stub(:save).and_return(false)
        post :create, {:diapositiva => { "pie_de_foto" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested diapositiva" do
        diapositiva = Diapositiva.create! valid_attributes
        # Assuming there are no other diapositivas in the database, this
        # specifies that the Diapositiva created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Diapositiva.any_instance.should_receive(:update_attributes).with({ "pie_de_foto" => "MyString" })
        put :update, {:id => diapositiva.to_param, :diapositiva => { "pie_de_foto" => "MyString" }}, valid_session
      end

      it "assigns the requested diapositiva as @diapositiva" do
        diapositiva = Diapositiva.create! valid_attributes
        put :update, {:id => diapositiva.to_param, :diapositiva => valid_attributes}, valid_session
        assigns(:diapositiva).should eq(diapositiva)
      end

      it "redirects to the diapositiva" do
        diapositiva = Diapositiva.create! valid_attributes
        put :update, {:id => diapositiva.to_param, :diapositiva => valid_attributes}, valid_session
        response.should redirect_to(diapositiva)
      end
    end

    describe "with invalid params" do
      it "assigns the diapositiva as @diapositiva" do
        diapositiva = Diapositiva.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Diapositiva.any_instance.stub(:save).and_return(false)
        put :update, {:id => diapositiva.to_param, :diapositiva => { "pie_de_foto" => "invalid value" }}, valid_session
        assigns(:diapositiva).should eq(diapositiva)
      end

      it "re-renders the 'edit' template" do
        diapositiva = Diapositiva.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Diapositiva.any_instance.stub(:save).and_return(false)
        put :update, {:id => diapositiva.to_param, :diapositiva => { "pie_de_foto" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested diapositiva" do
      diapositiva = Diapositiva.create! valid_attributes
      expect {
        delete :destroy, {:id => diapositiva.to_param}, valid_session
      }.to change(Diapositiva, :count).by(-1)
    end

    it "redirects to the diapositivas list" do
      diapositiva = Diapositiva.create! valid_attributes
      delete :destroy, {:id => diapositiva.to_param}, valid_session
      response.should redirect_to(diapositivas_url)
    end
  end

end
