require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DiasController do

  # This should return the minimal set of attributes required to create a valid
  # Dia. As you add validations to Dia, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "nombre" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dias as @dias" do
      dia = Dia.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dias).should eq([dia])
    end
  end

  describe "GET show" do
    it "assigns the requested dia as @dia" do
      dia = Dia.create! valid_attributes
      get :show, {:id => dia.to_param}, valid_session
      assigns(:dia).should eq(dia)
    end
  end

  describe "GET new" do
    it "assigns a new dia as @dia" do
      get :new, {}, valid_session
      assigns(:dia).should be_a_new(Dia)
    end
  end

  describe "GET edit" do
    it "assigns the requested dia as @dia" do
      dia = Dia.create! valid_attributes
      get :edit, {:id => dia.to_param}, valid_session
      assigns(:dia).should eq(dia)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dia" do
        expect {
          post :create, {:dia => valid_attributes}, valid_session
        }.to change(Dia, :count).by(1)
      end

      it "assigns a newly created dia as @dia" do
        post :create, {:dia => valid_attributes}, valid_session
        assigns(:dia).should be_a(Dia)
        assigns(:dia).should be_persisted
      end

      it "redirects to the created dia" do
        post :create, {:dia => valid_attributes}, valid_session
        response.should redirect_to(Dia.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dia as @dia" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dia.any_instance.stub(:save).and_return(false)
        post :create, {:dia => { "nombre" => "invalid value" }}, valid_session
        assigns(:dia).should be_a_new(Dia)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dia.any_instance.stub(:save).and_return(false)
        post :create, {:dia => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dia" do
        dia = Dia.create! valid_attributes
        # Assuming there are no other dias in the database, this
        # specifies that the Dia created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dia.any_instance.should_receive(:update_attributes).with({ "nombre" => "MyString" })
        put :update, {:id => dia.to_param, :dia => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested dia as @dia" do
        dia = Dia.create! valid_attributes
        put :update, {:id => dia.to_param, :dia => valid_attributes}, valid_session
        assigns(:dia).should eq(dia)
      end

      it "redirects to the dia" do
        dia = Dia.create! valid_attributes
        put :update, {:id => dia.to_param, :dia => valid_attributes}, valid_session
        response.should redirect_to(dia)
      end
    end

    describe "with invalid params" do
      it "assigns the dia as @dia" do
        dia = Dia.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dia.any_instance.stub(:save).and_return(false)
        put :update, {:id => dia.to_param, :dia => { "nombre" => "invalid value" }}, valid_session
        assigns(:dia).should eq(dia)
      end

      it "re-renders the 'edit' template" do
        dia = Dia.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dia.any_instance.stub(:save).and_return(false)
        put :update, {:id => dia.to_param, :dia => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dia" do
      dia = Dia.create! valid_attributes
      expect {
        delete :destroy, {:id => dia.to_param}, valid_session
      }.to change(Dia, :count).by(-1)
    end

    it "redirects to the dias list" do
      dia = Dia.create! valid_attributes
      delete :destroy, {:id => dia.to_param}, valid_session
      response.should redirect_to(dias_url)
    end
  end

end
