require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProgramasController do

  # This should return the minimal set of attributes required to create a valid
  # Programa. As you add validations to Programa, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "titulo" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProgramasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all programas as @programas" do
      programa = Programa.create! valid_attributes
      get :index, {}, valid_session
      assigns(:programas).should eq([programa])
    end
  end

  describe "GET show" do
    it "assigns the requested programa as @programa" do
      programa = Programa.create! valid_attributes
      get :show, {:id => programa.to_param}, valid_session
      assigns(:programa).should eq(programa)
    end
  end

  describe "GET new" do
    it "assigns a new programa as @programa" do
      get :new, {}, valid_session
      assigns(:programa).should be_a_new(Programa)
    end
  end

  describe "GET edit" do
    it "assigns the requested programa as @programa" do
      programa = Programa.create! valid_attributes
      get :edit, {:id => programa.to_param}, valid_session
      assigns(:programa).should eq(programa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Programa" do
        expect {
          post :create, {:programa => valid_attributes}, valid_session
        }.to change(Programa, :count).by(1)
      end

      it "assigns a newly created programa as @programa" do
        post :create, {:programa => valid_attributes}, valid_session
        assigns(:programa).should be_a(Programa)
        assigns(:programa).should be_persisted
      end

      it "redirects to the created programa" do
        post :create, {:programa => valid_attributes}, valid_session
        response.should redirect_to(Programa.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved programa as @programa" do
        # Trigger the behavior that occurs when invalid params are submitted
        Programa.any_instance.stub(:save).and_return(false)
        post :create, {:programa => { "titulo" => "invalid value" }}, valid_session
        assigns(:programa).should be_a_new(Programa)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Programa.any_instance.stub(:save).and_return(false)
        post :create, {:programa => { "titulo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested programa" do
        programa = Programa.create! valid_attributes
        # Assuming there are no other programas in the database, this
        # specifies that the Programa created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Programa.any_instance.should_receive(:update_attributes).with({ "titulo" => "MyString" })
        put :update, {:id => programa.to_param, :programa => { "titulo" => "MyString" }}, valid_session
      end

      it "assigns the requested programa as @programa" do
        programa = Programa.create! valid_attributes
        put :update, {:id => programa.to_param, :programa => valid_attributes}, valid_session
        assigns(:programa).should eq(programa)
      end

      it "redirects to the programa" do
        programa = Programa.create! valid_attributes
        put :update, {:id => programa.to_param, :programa => valid_attributes}, valid_session
        response.should redirect_to(programa)
      end
    end

    describe "with invalid params" do
      it "assigns the programa as @programa" do
        programa = Programa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Programa.any_instance.stub(:save).and_return(false)
        put :update, {:id => programa.to_param, :programa => { "titulo" => "invalid value" }}, valid_session
        assigns(:programa).should eq(programa)
      end

      it "re-renders the 'edit' template" do
        programa = Programa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Programa.any_instance.stub(:save).and_return(false)
        put :update, {:id => programa.to_param, :programa => { "titulo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested programa" do
      programa = Programa.create! valid_attributes
      expect {
        delete :destroy, {:id => programa.to_param}, valid_session
      }.to change(Programa, :count).by(-1)
    end

    it "redirects to the programas list" do
      programa = Programa.create! valid_attributes
      delete :destroy, {:id => programa.to_param}, valid_session
      response.should redirect_to(programas_url)
    end
  end

end
